### ISSUE TITLE
GAIL Training - Train the policy net fist with behavioural cloning and fine tune with the GAIL ?

### ISSUE THREAD

**Issue by shamanez** [uidilr/gail_ppo_tf#9]
Hi can you merge this in a efficient way to the code? Or can you give me some advice where should I load the pre-retrained weights to the policy network ?

Next Question - What do you think about training GAIL with high dimensional data ?  Let's say with images ?

**Comment by uidilr** [comment]
I gave it try to use pre-training weight once, but training is failed.
Since I deleted that code, I will just give some advices. 

1. Define new saver of trainable variables in the policy net.
2. Load the pre-trained weights after this line, 
https://github.com/uidilr/gail_ppo_tf/blob/f8f496f69c2a166e91164d9082d7f9fd5a80b6b5/run_gail.py#L36


> Next Question - What do you think about training GAIL with high dimensional data ? Let's say with images ?

I think it is difficult to solve. This is all I can say.

**Comment by shamanez** [comment]
Training failed means your code didn't work or It's the training procedure or the accuracy?

**Comment by uidilr** [comment]
It means that accuracy did not improve.

**Comment by shamanez** [comment]
Can you explain one thing about the pre-trained GAIL model you have given in the trained models?  How long it took to converge?  ALso the specs of ur machine
